name: Ansible EC2 Provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  provision-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python & Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install --user ansible boto3 botocore
        ansible-galaxy collection install amazon.aws

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Create SSH Key File
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    - name: Debug SSH Key
      run: |
        ls -l ~/.ssh/ec2_key.pem

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbooks/provision_and_config_server.yml \
        -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SSH_PRIVATE_KEY: ~/.ssh/ec2_key.pem
        ANSIBLE_HOST_KEY_CHECKING: false